export const randomActivity = [
    "Just passing through (passive)",
	"Hunting for game (aggressive)",
    "Hunting for game (aggressive)",
    "Hunting for game (aggressive)",
    "Hunting for game (aggressive)",
    "Hunting for game (aggressive)",
    "Hunting for game (aggressive)",
	"Guarding or patrolling their territory (aggressive)",
    "Guarding or patrolling their territory (aggressive)",
    "Guarding or patrolling their territory (aggressive)",
	"Looking for something (treasure, a dungeon) (aggressive)",
	"Hunt down escaped prisoners (passive)",
	"Searching for water (passive)",
    "Searching for water (passive)",
    "Searching for water (passive)",
	"Homesteading (passive)",
	"Migrating to another territory (passive)",
	"Fleeing a dragon or other monster (passive)",
	"Undergoing a spirit journey or coming of age quest (aggressive)",
	"Pilgrimage to a holy site (passive)",
	"Retreating from a battle with other rival monsters (passive)",
	"Going to attack rival monsters (aggressive)",
	"They just live around here as a hermit (passive)",
	"Going to find new slaves (aggressive)",
	"Looking for sacrifices for a ritual (aggressive)",
];