export const forest = [
    "A gnarled tree stands in an otherwise normal grove; its trunk looks like a petrified humanoid.",
    "A dry ravine cuts across the path; it is five-foot-wide and ten-foot-deep.",
    "An abandoned campsite sits a few hundred feet from the trail; the campfire still burns, and camping gear litters the area.",
    "A hut stands near the path; it is uninhabited, but many shrunken heads decorate the place.",
    "The trail forks into two separate trails that meet up a mile further (a mile and a half for the other, meandering trail).",
    "A wide river cuts across the trail; a covered bridge spans the river.",
    "A huge footprint crosses the path; the print is a couple hundred years old and does not lead to other footprints.",
    "The crowns of this grove of trees uniformly bend in the same direction.",
    "This old battleground shows signs of arcane fire magic; no weapons or treasures remain.",
    "A series of underground homes line the path; they are abandoned but appear to have housed a gnome clan.",
    "A large mound of rusted iron sits forlornly in a barren field.",
    "A grove of willow trees sits within a ring of vegetation that appears to have been destroyed by frost.",
    "A large tree has fallen across the trail and completely blocked it.",
    "A cave, looking much like a monster’s maw, becomes evident as the party crests a hill.",
    "A small settlement of ten houses lies empty; the houses have had their roofs ripped off.",
    "A saltwater pond filled with marine life sits near the trail; freshwater fills nearby ponds.",
    "A set of steps climb a nearby hill; each step is ten feet wide, five feet tall and made of material unique to each step (granite, iron, etc.).",
    "A ring of eight-foot-tall toadstools surrounds a lone 40-foot-high oak tree.",
    "A shallow slope leads into an underground cavern; large insect husks litter the floor.",
    "This campsite appears to have been attacked by large animals; tents are torn, food is scattered around, and splotches of blood cover the ground.",
    "Vines and brambles cover the tumbled pile of stone that was once a manor house.",
    "Here, four large trees have grown so closely together their trunks and branches have become intertwined. The trees grow along a high earthen bank and form a formidable barrier.",
    "A deep natural amphitheatre stands empty among the trees.",
    "An empty, 30-foot-diameter beetle’s black carapace lies amid the trees and can provide shelter from the elements.",
    "Large granite spires form four-fingered hands.",
    "A perfectly circular lake surrounds a flat, perfectly square island.",
    "This 100-square-foot field of beautiful blue flowers fills a wide clearing.",
    "An ancient, overgrown grave lies near the path; the stone is weathered and unreadable.",
    "The land is cleared to form an ‘X’; each line measures fifty feet long.",
    "Columns of willow trees flank the path, creating a natural archway.",
    "Colourful ribbons cover the trees. They use varying shades of blue, purple and red. Many bear short prayers or names; these trees are sacred to a nearby community.",
    "A lone tree with copper plates affixed around its trunk stands in a clearing. The tree is scorched and burnt as if repeatedly struck by lightning.",
    "The gutted and rotting, expertly butchered carcass of a deer lies in the undergrowth near the trail. It has obviously lain here for weeks.",
    "This clearing holds an ancient ring of weather-worn menhirs. At noon and during a full moon, the stones sparkle as if inset with precious gems.",
    "The characters find the leavings of a battle evidently between fey creatures under a small cluster of mushrooms. No bodies remain, but tiny bows, swords and lances litter the battlefield.",
    "Partially uprooted trees lean into each other as if they huddle against each other for support.",
    "Chalk arrows on trees point out a path but end without reaching an obvious destination.",
    "A large beehive hangs from a sturdy branch; as long as the party stays more than twenty feet away from the hive, the bees do not attack.",
    "Deep ruts in the ground create a wide area of difficult terrain. If it has rained recently, water fills the ruts, further slowing movement in the area.",
    "A shallow, malodorous bog covers part of the path. Anyone passing through the mud gets covered in muck and gives off a pungent odour until they wash.",
    "A gnarled oak that appears like a contemplative old man sits near an enormous boulder; the boulder hides the entrance to a forty-foot diameter cave. A small pool at the rear provides fresh water.",
    "A tall tree features its first strong branch 20 feet off the ground; this branch has a hangman’s noose tied to it, but no creature hangs from the rope.",
    "A thick patch of poison ivy covers a ruined, part-collapsed hovel.",
    "A quick-moving stream blocks the way; a fallen, rotting tree bridges it.",
    "A lone tree stands in a clearing; someone has decorated the tree with brightly-coloured garlands and bunches of wildflowers; no other nearby trees are so decorated.",
    "Loggers have clear-cut this area; however, they have left a pair of trees untouched. There is no apparent reason the trees were spared.",
    "Several unusual fungi specimens grow in this area; they look like brains set on spinal columns.",
    "A trio of trees bear strange, round and unnatural yellowy-green leaves.",
    "A large tree has partially fallen; its fall was arrested by a smaller neighbour. The fallen tree lies over the trail, creating an archway of sorts.",
    "A wooden trapdoor hidden underneath a pile of leaves and branches protects a cache of trail rations and water.",
    "A pond rife with lily pads fills a large clearing; the pond may or may not be the home to a teeming group of frogs. Trees crowd close to the pond, throwing much of it into shade.",
    "A tree grows two feet up before its trunk twists perpendicularly so it is parallel to the ground; the trunk then turns straight upward again after another four feet. The trunk is sturdy enough to hold 1,000 pounds on its horizontal portion.",
    "An abandoned bandits’ hideout is poorly hidden behind a row of trees; several old campfires and piles of rubbish bear mute testimony to the bandits’ presence.",
    "A grove features trees with twisted trunks as if a tornado attempted to uproot them. The trees are otherwise healthy.",
    "A large oak’s trunk has etched ancient dwarven runes on it; the faded runes provide directions to a hidden mountain fortress, which may or may not still be occupied.",
    "A blackened tree sits among hearty specimens; its leaves withered. It could be a victim of rot, or it could be cursed.",
    "Normal trees give way to giant sequoias and redwoods; the smallest tree stands at least 100 feet tall, and their lowest branches are 40 feet from the ground.",
    "A grove of pine trees shelters animals that would otherwise be natural enemies (wolves, foxes, rabbits, deer and so on); they remain peaceful even if the characters approach.",
    "A small home sits amid the branches of a large tree; the inhabitants—halflings or gnomes by the decor—have abandoned their home.",
    "The pathway descends steeply; rough steps—edged with half-buried tree trunks—have been cut into the earth.",
    "The path ends abruptly at a 50-foot-high cliff, but trees grow from the side of the cliff; climbing up or down is easy.",
    "A grove of fruit trees bears multiple different types of fruit—apples, pears, peaches and so on.",
    "The trees in the area have tacked-on signs proclaiming death to trespassers; the “by order of” line has several marked-out names, with no name currently uncrossed.",
    "Rope bridges link the trees here; the bridges hold creatures weighing less than 500 pounds and allow the party to cross the forest aboveground for several miles.",
    "Wind and water erosion have revealed a vein of precious metal; it would require several months and heavy equipment to extract the metal.",
    "Fibrous creeping vines cover the entirety of this one-mile swath of forest; the trees they cover seem to be dying while the vines continue their rampant growth.",
    "Moss-covered bones from a large creature lie in a clearing; this was an adult green dragon.",
    "These trees are petrified—their bark has the consistency of shale, and their leaves even appear to be made of thin stone.",
    "The trees here have faded paintings depicting a series of great battles between a giant and a sky serpent on their wide, gnarled trunks; the primitive tribe responsible for the paintings is long since gone.",
    "A dilapidated house sits within a ring of dead trees; the trees have been carved with runes to prevent creatures from exiting the ring of trees. (A wizard can identify the runes.) If the characters investigate, they find nothing in the house and may freely leave the circle.",
    "The canopy thickens so much daylight cannot penetrate a 100-foot-radius stretch of forest.",
    "The path comes upon an area containing well-maintained topiaries of fantastic creatures, such as griffons, manticores and unicorns.",
    "A large meteorite that struck here over 100 years prior lies hidden within a glade; characters camping nearby may uncover the meteorite, which may contain unusual metal such as mithral or adamantine; extracting such treasures is difficult.",
    "Blue moss covers the trees; at night, the moss glows with the brightness of a torch. If the moss is deprived of daylight for two days, it does not glow until it gets a full day’s exposure to sunlight.",
    "Two dozen rabbit burrows are situated among the roots of a huge tree; in total, over 400 rabbits inhabit the burrows.",
    "A small stream oozes from a muddy bank. A ten-foot section of the path is knee-deep in mud.",
    "A grove of uncultivated apple trees grows in orderly rows and columns.",
    "This clearing holds ten untripped snares and two tripped traps that hold skeletal remains of animals; the traps have been here for at least a year.",
    "A family of beavers has dammed a large stream; at least 40 animals tend to the structure that holds back the eight-foot-deep water. A trickle of water spills over the top of the dam.",
    "The east side of all the trees in this part of the forest is stripped of bark as if something took a blade to flense just that portion of each tree.",
    "Masses of uninhabited spider webs fill the gaps between the trees; searching the area uncovers several spider husks.",
    "A tall wooden totem stands among the trees; it is fashioned from the same wood as the surrounding trees and features artisanship belonging to a culture not of this area.",
    "A single tree features a brass doorknob; turning the knob does nothing, and inspecting the tree does not reveal a door or hollow area within.",
    "Tall grasses grow among the trees; the grasses bend in the breeze.",
    "This is a treant graveyard; many of the creatures lay in rows, rotting away but providing nutrients for saplings—young treants—growing here.",
    "This otherwise normal stand of trees forms a rune that a flying creature can read; this layout is invisible from the ground.",
    "The trees in this area have 6- to 12-inch-long nettles entwined ten feet up their trunks; anyone with any nature knowledge knows nettles do not normally grow in this manner.",
    "The aspens here glow with a silver light during nights with a full moon.",
    "The trees grow so densely here Small or larger creatures must squeeze to get through. The light level is one level lower here than normal.",
    "Nests, ranging in size from those for small birds to those for giant eagles, fill the canopy overhead. Only the smaller nests contain birds.",
    "This clear pond is filled with weak acid; the acrid smell and lack of wildlife give away this fact. The pool sits to the side of the trail.",
    "A part-built log cabin sits near the path; its missing roof makes it a poor choice for shelter. Several cut logs rest next to the cabin, waiting to complete the abandoned task. Rusting tools lie about the area.",
    "The leaves on this unusual tree bear an image that looks like a humanoid eye; the leaves’ eyes seem to follow those who pass by the tree.",
    "These trees are fleshy rather than made of plant material; if someone cuts through a tree’s skin-like bark, the tree bleeds.",
    "An exceptionally tall tree stands among the other trees; someone has nailed a wooden ladder to its trunk. The ladder climbs the tree trunk’s entire 60 feet, and the top gives a clear view over the forest.",
    "All trees in this area have bleached tree bark; the leaves retain their green, albeit pale, colouration, and the trees appear otherwise healthy.",
    "The trees in this portion of the forest move very slowly about; each tree moves approximately one inch every 24 hours. The migration’s purpose is not obvious, but a character who can speak with plants may be able to learn it.",
    "Scrolls tacked to the trees contain unanswered riddles; anything written as an answer below a riddle has been obscured. If the characters decide to mark a scroll with an answer, they find their work obscured after a maximum of a week.",
    "The trees in this area form a simple maze; solving the maze takes 15 minutes for a creature with a 30-foot movement rate. An ancient treant waits at the maze’s centre to speak with visitors."

    
];

export const grassland = [
    "The tumbled remains of a stone wall denote the boundaries of a long abandoned farm.",
    "Many rabbit burrows pierce a mud bank. Abundant rabbit tracks mar the mud.",
    "The burnt-out frame of a barn stands stark against the sky.",
    "The entrance to a mine is boarded over. A sign warns of the dangers of collapse.",
    "A lonely, massive oak tree stands alone amid a sea of grass.",
    "A low area of scrub conceals a traveller's half-eaten remains.",
    "A loose sign spins on its post, ironically trying to point to 'the city.'",
    "A gate stands at the edge of a field, but there is no fence. A sign proclaims: 'Tawcket’s Place.'",
    "A set of squared stones is laid out in the crude imitation of a man.",
    "An ancient statue stands at a crossroad, pointing to the eastern fork. Its inscription is barely visible—the words lost to time.",
    "The burnt-out remnants of a wheeled canvas wagon lie near the path.",
    "A spent oil lamp, its brass tarnished nearly solid green, perches atop a tree stump.",
    "Wild roses grow as far as the eye can see.",
    "A cornfield has been shaped into a simple maze, but much of the crop has now been harvested.",
    "Much of this grain field has been flattened, forming eldritch patterns.",
    "A circle of stones sits around a well-used fire pit. An assortment of candles and other arcane paraphernalia fill a nearby concealed hollow.",
    "A thick, tangled growth of brambles fills a natural hollow near the path. Wild blackberries and other fruits grow among the tangle.",
    "A crater stands as a blemish in an empty field.",
    "The shattered remnants of a porcelain tea set frame a wagon rut.",
    "An empty noose swings from a tall tree.",
    "The nearby farmhouse has been abandoned for at least a decade.",
    "A pool of stagnant water stands amid a field of bright orchids.",
    "The only proof a building once stood here is a lonely archway in a weed-filled field.",
    "A nearby pond is frozen solid, no matter the ambient temperature.",
    "A sign on an unattended cart proclaims, 'fresh fruit for sale: 1 copper.' The fruit looks fresh.",
    "A nearby tree is laden with overlarge golden fruit ready to eat.",
    "The half-concealed skeleton of an enormous beast dominates an otherwise barren field.",
    "The stones of this bit of wall are scattered throughout this field as if smashed inwards.",
    "Many animal tracks crisscross the muddy trail.",
    "Wind-swept leaves fill a shallow hollow.",
    "Arcane sigils cover a stone that sits just off the beaten path; at night, they glow faintly.",
    "A shattered wagon wheel, heavy with moss, lies half-buried nearby.",
    "Wild strawberries grow haphazardly throughout a nearby field.",
    "A handful of toppled columns are all that remains of a temple that once stood here.",
    "Half-buried skeletal remains paint a picture of a conflict fought long ago.",
    "A toppled tree stands as an improvised bridge across a shallow, dried stream.",
    "This field may once have held bountiful crops, but it is now nothing but burnt stubble.",
    "A skeletal arm thrusts from the ground clutching a shimmering blue silken scarf.",
    "A small pool throws twisted reflections back at the party, showing subtle changes such as different hair or eye colours.",
    "A weathered stone covered in thick moss appears to have been a statue long ago.",
    "The flag of a far distant nation proudly stands ahead, flapping in the wind.",
    "Simple wooden markers are the only indication of a roadside graveyard.",
    "A faded sign is adorned with a simple spiral pattern in flaking yellow paint.",
    "The skeletal remains of a human are staked out in a nearby field. Around its neck is a wooden placard that reads: 'Witch, Heretic, Lover.'",
    "Ancient rusted manacles and a grey tunic with the device of a local lord are stashed between the roots of a tree.",
    "Worn holes in a stone monument cause the wind to pierce the air in fierce howls.",
    "A half-finished stone wall almost surrounds a well.",
    "An owlbear’s bones lie in the scrub.",
    "The remains of an old campsite overlook the road from among a shrine's tumbled ruin.",
    "A fire-damaged mirror lies nearby, distortedly reflecting the sky as though it were ablaze.",
    "A well-built chest stands unguarded under a tree.",
    "A desolate windmill stands near the decrepit remains of a farmhouse.",
    "Monstrous boulders stand off the road nearby, forming a set of concentric circles.",
    "A weathered shield lies nearby, its heraldry that of a family dead nearly a century.",
    "Shattered lances and heavy hoof prints surround a short length of wooden fence.",
    "An unlit funeral pyre stands atop a rise; the body atop the pyre is now skeletal.",
    "A tall stone has been carved into a sculpture depicting a hero overcoming a terrible beast.",
    "Bones litter the floor of this part-collapsed hut.",
    "The half-eaten remains of a goat lie on the trail.",
    "The shattered remains of a stone gargoyle are scattered about this field.",
    "Shattered wine glasses and an empty bottle surround a well-used campsite.",
    "A flag of a nearby kingdom flutters proudly from a nearby hilltop.",
    "Brilliantly coloured flowers line the trail for the next three miles.",
    "Crossbow bolts pepper the area; 2d6 of them are in good enough condition to use.",
    "A stream meanders down a hill and cuts through the path; the party can use the ford or dare the stepping stones further downstream.",
    "Two dozen glittering silver coins surround a ruined burlap sack.",
    "Rubbish—the leavings of a nearby settlement—fill a small gorge.",
    "Enormous pieces of eggshell suggest something ate well here.",
    "A huge piece of claw appears to have been shed by a griffon sharpening its nails on a tree.",
    "Pieces of a sundered crossbow lie about the trail.",
    "Chunks of volcanic glass are laid out in a simple message: 'Leave.'",
    "A statue is frozen with horror as it points toward a set of six-legged lizard tracks.",
    "Three-quarters of an arch, its keystone a leering skull, defies gravity to hang over the path.",
    "A massive battleaxe lies in the ruins of this small cottage; giant footprints surround the ruin.",
    "A dense patch of mushrooms grows in the lee of a fallen, rotted tree.",
    "A tumbled dry stone wall runs parallel with the track for a hundred yards before petering out.",
    "A small patch of bright red mushrooms stands jarringly in this field of green grass.",
    "Wild raspberries have overgrown a manticore's skeletal remains.",
    "A red-stained stump stands at the head of a pit filled with the rotting remains of various animals. A gilded axe is planted in the stump.",
    "These glittering beetle shells are easily mistaken for gemstones from a distance.",
    "Half-buried glass bottles surround an old camp.",
    "Scattered bone and stone weapons surround a tall black monolith.",
    "Clouds form the shapes of two duelling monsters; the wind makes their movements seem lifelike.",
    "The dirt here is stained with bright colours as if splattered with paint.",
    "This iron cage has been torn open from the inside by something powerful.",
    "Ragged tears suggest a large animal has been sharpening its claws on a nearby tree stump.",
    "A well-made hat sits atop a mound of stones crudely piled to resemble a man.",
    "Several cut and dressed large stone blocks lie by the side of the trail; weeds grow about them.",
    "The foundations of a large building have been laid, but no structure was ever built.",
    "A sheltered pool fills much of a hidden dell. A faint and steep trail leads down to the pool.",
    "The corner of this way marker has been carved with monstrous visages.",
    "Water oozes from a nearby bank and turns the path into a muddy bog.",
    "Dozens of silver and copper coins, worth almost 50 gp total, fill this shallow well.",
    "A rocky hill overlooks the trail; the smoke of a campfire rises into the air behind it.",
    "A decapitated bronze statue, heavy patina covering the body, watches over the trail. The head—lying nearby—is well-polished.",
    "The contents of a traveller’s backpack are neatly laid out on a tree stump.",
    "The trail crosses the shed skin of a snake nearly 10 feet in length.",
    "The dirt here has been churned by the crossing of dozens of wheeled vehicles.",
    "A broken wagon wheel lies discarded by the trail.",
    "A weathered mile marker stands half-covered by weeds and brambles.",
];

export const hills = [
    "Tucked into a small grotto stands the burned husk of a miner’s cabin.",
    "A large patch of morel mushrooms sprouts from the ground in a boggy dell.",
    "A thick growth of wild raspberry bushes has a path roughly chopped through it.",
    "A recent rock slide partly covers the underbrush.",
    "An old game trail crosses the trail; roll a 1d6: 1 tracks from a wild turkey, 2-4 no distinct tracks, 5 tracks of soft-heeled boots, 6 bear scat.",
    "A wild strawberry patch grows in the hollow between two low, grassy hills.",
    "The characters find a small cairn of flat slate stone surrounded by wildflowers.",
    "A scrap of red silk is caught in the thorny grip of a wild white rose bush.",
    "The path widens; a vine-covered cart with two broken wheels rests on the side of the trail.",
    "A hollow among three steep hills drops into a 40-foot-deep sinkhole.",
    "A dilapidated hunter’s cabin leans uneasily against a rocky hillside.",
    "The low, broad outline of a stone archway pierces the grassy side of an evenly rounded hill.",
    "Piles of tall grass lie in neat piles. Lazy smoke rises skyward from behind the hilltop.",
    "Stunted blueberry bushes huddle about a small sunken pool of clear water.",
    "A woodsman’s axe lies on the ground next to a pile of cut wood. Dried blood covers the axe.",
    "The dry heat of the sun has baked dry, cracked faces into the sparsely covered hills.",
    "A group of semicircular hills rise in the distance; large, flat stones top all three.",
    "The tumbled remains of a watchtower top a gently sloped hill.",
    "This section of trail has been dug into the side of a hill, doubling its width.",
    "A large earthen berm circles a ruined and abandoned hamlet.",
    "An exposed deep hole between adjoining hills opens into a cavern.",
    "A ten-foot-thick archway cuts through a gigantic tree between two hills.",
    "As the trail ascends a steep hill, ancient flagstone steps are visible beneath the mud.",
    "The remains of a crumbling tower cascade down one side of this rocky crag of a hill.",
    "An outline of a giant man is laid out in stone on the hillside a few bowshots ahead.",
    "Two sharply rising hills flank the road.",
    "A tall wooden tower perches atop a hill in the distance; it appears unoccupied.",
    "Large flat stones etched with illegible symbols cover a hilltop. This is an ancient burial site.",
    "The trail wends through closely crowded hills. Travellers must move in single file.",
    "Dishes outside a small roadside shrine contain mouldy cheese, bread and herbs and a small tiger eye agate (worth 10 gp).",
    "A low oblong hill, covered in tiny white and purple flowers, has crude steps cut to its flank.",
    "A massive 100-foot-deep crater pierces a hilltop’s northern face.",
    "Lines of dark hawthorn trees flank the path through the hills.",
    "A tight, small grove of crab-apple trees wreaths the top of a hill to the north.",
    "A low, crumbling moss-wreathed stone wall snakes its way downhill.",
    "The smashed remains of a wooden bridge fill a narrow gorge.",
    "Vines and underbrush grow thickly over the steps and walls of a ruined cottage.",
    "A rock shelf juts out over a low opening at the base of the hill.",
    "A broken circular stone platform stands at the centre of this earthen amphitheatre.",
    "This small roadside shrine has been vandalised.",
    "An opening of an old mine shaft is supported by stout oak posts bleached white by age.",
    "A narrow chasm slices the hill in half. Thick underbrush and thorny bushes hide it from view.",
    "A tight stand of birch trees covers a lone hill.",
    "A sturdily built, weed-choked wooden fence climbs its way up the hillside.",
    "A hill of coarse and pitted black volcanic rock rises and falls like a wave amid the other hills.",
    "The trail ends abruptly at the base of a steep hill.",
    "Piled stone battlements, no taller than a goblin, squat about the base of a low hill.",
    "The hillside provides ample cover for any creature traversing it.",
    "Patches of mist drifting up from below cloak the grey-green face of this cliff.",
    "The twists and turns of the low foothill gullies have become rocky, like a dry riverbed.",
    "The crumbling remains of two massive pillars carved with devils’ faces flank the trail.",
    "This lone half-timbered shack’s mouldering thatch roof has partially collapsed.",
    "Several pecan trees laden with green-skinned immature fruit grow across a hillside.",
    "A grassy plain thickly coated with wildflowers covers a nearby plateau.",
    "A flat hill flanks the trail. Atop it, a windmill with broken sails stands forlornly in splendid isolation.",
    "A low bluff slopes up to a rocky prominence; its shape is vaguely pyramidal.",
    "A wind-hewn tor stands atop a steep crag. The tor vaguely resembles a five-finger hand.",
    "The limestone face of this broken crag is dotted by blue spruce pine and their fallen kin. A chimney crack splits the crag’s face.",
    "Grass grows along a ridge like a receding hairline.",
    "Gorse, low bushes and weeds cloak the foundations of an old, abandoned village.",
    "Two huge boulders, one piled precariously onto the other, stand by the trail.",
    "A gurgling rill runs away from a small waterfall. A rudimentary bridge of flat stone crosses the rill.",
    "Cold winds, blowing a ripped and torn cloak, whistle down the trail.",
    "A blackened hill looms above the trail. Scorched and charred vegetation shows where a fire raged.",
    "A deep crack in a cliff overlooks the trail. Inside, a slope leads down to a small, dry cave.",
    "Five stones stand at the base of the hill. From the pile, a small game trail snakes into the bushes.",
    "The slopes of the defile rise like a tear in the hillside. Shadows shroud the path.",
    "A broad, shallow valley opens up ahead. Wildflowers cover the ground.",
    "The path splits, leading off in five directions. Three of the paths are well-travelled.",
    "The deeply eroded hillside exposes loamy, black soil. Root balls of tall grass hang from the sod.",
    "An extremely jagged hill provides cover from the wind that whips about this high spot.",
    "A heavily reinforced stone door pierces a cliff.",
    "Four switchbacks zigzag up the steep hills. A large cairn of stones stands at each turn.",
    "A difficult path runs up the rocky hill face. Its edges crumble away if anyone gets too close.",
    "A near-perfect rock dome tops the hill. Black cracks cover the web-shaped dome.",
    "Terraced hills form small farm plots. The plots are overgrown and abandoned.",
    "A whistling sound caused by wind moving through gaps and crevices in the hillside fills the air.",
    "A small abandoned mining settlement sprawls over the gentle slope of this hill.",
    "A steep, massive tor rises from a hillside. A lone watchtower perches at its zenith.",
    "A side path runs between two small mounds linked by a crumbling and cracked stone archway.",
    "The form of several sharp outcrops on the hillside are suggestive of leering faces.",
    "A wind-worn flat rock faces the rising sun. Its mirror-smooth surface glints brightly.",
    "Thin, foot-long grass-green crystals protrude like spines from both sides of the hillside path.",
    "The tall grass growing here is twisted into tight spiralling bundles.",
    "The dry wash below a hill opens into a small basin.",
    "A massive sinkhole nearly engulfs the base of a high, sheer rocky hill.",
    "Slabs of black obsidian coat the low hill like armour. An archway pierces the hill’s flank.",
    "Sulphurous, terraced pools of hot water flank the trail. Stinking mists fill the air.",
    "A small cave mouth lies at the back of a grotto.",
    "Tucked between two hills, boiling mud pits roil with heat and noxious gasses.",
    "Foresters’ huts dot the hills bordering the forest. Much cut lumber is piled about.",
    "A colony of ants fills the cracks in this cliff.",
    "Slimy, iridescent pale blue mushrooms cover this deeply shadowed hillside.",
    "The path winds down a steep, sparsely grass-covered hillside like an undulating serpent.",
    "A starkly bright lichen-covered rock juts from a cliff. Its huge overhang could shelter five humans.",
    "The wall of a broken well stands at the base of an overhanging bluff.",
    "Deeply eroded red clay blankets this section of rolling hills.",
    "Wedged between the rocks halfway up this hill stands a stone hut. A slow pillar of smoke drifts from its chimney.",
    "The hill path ends at a precipice that drops hundreds of feet to the foothills below.",
    "An entire hill face is carved with a 30-foot high relief of a mythical beast."
];

export const monuntains = [
    "A small ruined lookout tower perches atop a conical hill.",
    "Strange circular geometric patterns cover the ground just above the tree line.",
    "Deep fissures cut through the ground.",
    "A small village huddles out of sight under a massive rock overhang.",
    "A narrow switchback trail ascends the cliff.",
    "Bright white and black speckled marble slabs are piled through the pass.",
    "A lake fills the valley between two mountains.",
    "Loose rocks and large boulders bear witness to an old avalanche.",
    "The taste of limestone dust fills the air of a narrow mountain gorge.",
    "Three trees cap a mountainous ledge.",
    "Two ten-foot-tall obelisks flank the narrow trail leading into a valley.",
    "Many cracks in the mountain’s glacier face form a jagged serac.",
    "A sturdy dwarven bridge spans a 30-foot-wide, 80-foot-deep chasm.",
    "A 40-foot-high rough escarpment of sandstone rises nigh vertical.",
    "A circle of petrified tree stumps overlook the valley below.",
    "Rounded at its edge, the lip of this cliff slopes down in a gentle but progressive curve.",
    "The entrance to a small, played-out mine pierces a cliff face.",
    "Rock columns—large boulders balanced atop one another—litter a sheltered valley.",
    "Like an ocean coast, the tree line zigzags below the snow cap of the mountain.",
    "The valley floor opens up to sparse ground cover. Natural fairy chimneys dot the valley.",
    "A giant stone anvil inscribed with weathered and unreadable runes rests upon a stone dais.",
    "Sheets of slate grey rock lie scattered along the mountain trail.",
    "A series of ledges jut from the cliff face.",
    "In a wide culvert off the trail, a narrow set of carved steps ascends the cliff.",
    "A 50-foot-high bas-relief carving of a snarling humanoid decorates the cliff overlooking the trail.",
    "This natural wind-carved arch spans 50 feet from one cliff face to another.",
    "A 15-foot-deep cave opens under a jutting overhang. Deep darkness clusters within.",
    "Six dangling corpses hang from the brink of a high cliff and sway gently in the wind.",
    "Pink and white veins of marble run up the wind-blasted cliff.",
    "Swirls and undulating waves of sandstone form smooth bowls throughout this part of the range.",
    "Rising from the glacier sheet high in the mountain stands a nunatak of black rock.",
    "For almost 2,000 feet, a series of waterfalls and plunge pools drop down the entire cliff face.",
    "A single shelf of rock slopes up toward a small hole in the cliff.",
    "Towers of stone jut from the mountain valley floor, like stone trees.",
    "Sheer cliff walls of dark grey granite hem in this deep gorge.",
    "The trail breaks onto a thirty-foot-wide 'rock pulpit' high above the valley floor.",
    "An ice-covered shoulder of the mountain extends toward the north.",
    "A dry, cold and desolate rubble-strewn desert has formed on the lee side of this ledge.",
    "A steep-sided, lofty plateau emerges from its gossamer mist-shroud.",
    "A shifting swath of dull brown scree skirts the foot of the mountain, halving all land movement.",
    "The steep slopes of this gorge descend into the turquoise water of a river far below.",
    "The shallowness of the col between two peaks gives them the appearance of teeth.",
    "By the light of the setting sun, a rock formation looks to be that of a troll’s face; thick, coarse grass sprouts from its forehead.",
    "Rising to the highest of all the peaks, this mountain reaches 26,414 feet into the sky.",
    "Banded strips of red sandstone curve smoothly in slow arcs through this part of the range.",
    "Folding backwards toward the east, this mountain has towering roof-like overhangs.",
    "Tall, carved wooden totem poles flank the trail.",
    "The snowline dips low into the treeline.",
    "Vast swaths of wildflowers cover the floor of this shallow, sunlit mountain valley.",
    "A crown of darkly coloured transparent blue-tinted ice rests atop this mountain’s summit.",
    "Towering walls of ice coat the rock wall just before the summit of a nearby mountain.",
    "An expansive moraine sits just below the mountain’s glacier.",
    "This culvert in the rock is made distinct by the one-inch-long crystals protruding from its walls.",
    "A deep ice cave opens at the foot of a glacier.",
    "Hundreds of shallow natural bowls worn into the rock cover this wide plateau. Each holds a few mouthfuls of water.",
    "The ruins of a watchtower loom over the trail.",
    "Dusty brown and red sandstone ridges stretch to form a long valley.",
    "A partially buried watch tower is smothered under a long-past landslide.",
    "Deep interconnected amphitheatres of brightly coloured limestone form a giant maze.",
    "Only as wide as a halfling, this chimney crack rises all the way up a cliff.",
    "A narrow eight-foot-long rock needle protrudes from the cliff face above the trail.",
    "Placed in erratic spots about the valley, huge boulders are spaced widely apart.",
    "Standing alone, a narrow plateau is pierced through its centre by a 20-foot-diameter hole.",
    "The jagged ridge line of the mountain drops to a cliff. A small keep dominates the ridgeline.",
    "Many small lakes fill this mountainous valley.",
    "A wide brow of rock overhangs a long-abandoned clifftop village.",
    "The view from this mountain’s summit looks down on the tops of thick clouds.",
    "The trail leads down a steep slope of scree. Travellers must move cautiously or fall.",
    "A series of terraced gardens rise towards an old tottering keep.",
    "Rising 60 feet up the cliff, a carved crack has a four-foot-square hole near its centre. On misty days, a rainbow emerges from the hole.",
    "Snow and ice cap the nearby mountain peaks.",
    "A precarious pile of rocks overlooks the trail. Set high on a ledge, they could easily be pushed down onto those below.",
    "A ramshackle roofless shack sits near a swiftly flowing river.",
    "Dramatically hanging near the summit, a horn of rock protrudes from the mountain’s face.",
    "A huge scorched rock lies near the trail. It has been split in half by some tremendous force.",
    "The mountainside rises like a curtain wall in a near-vertical face.",
    "Pinned into a deep dead-end valley rots a festering mountain bog.",
    "Flat-topped rock outcroppings provide good views of the surrounds.",
    "Savage wind whistles down from the highest peaks, extinguishing exposed flames and taking travellers’ breath away.",
    "Rising high above the clouds, a bare mountaintop looms like a balding head.",
    "A twenty-foot-deep overhang of rock hangs above a narrow ledge. A small cave opening hides deep within the shadows below the overhang.",
    "Only sparse grass grows on this swath of wind-blasted rock.",
    "This peak is only accessible during the early spring months. Otherwise, it is covered in deep, light powdery snow.",
    "An ancient burial cairn set on an exposed sliver of rock overlooks a valley.",
    "Water fills long, deep grooves in the rock.",
    "The bare slopes of a mountain descend to a placid, sheltered lake.",
    "Wind blowing from a deep, gaping cave mouth creates a loud moaning sound.",
    "Small cairns mark the winding footpath leading up the mountain flank.",
    "Perched high above on a small plateau squats a lone two-storey building.",
    "Thick, dark, loamy soil riddled with weeds covers the ground.",
    "The dazzling sparkle of white and orange quartzite makes the rock face nearly blinding to look at.",
    "The ruins of a mountain watchtower protrude from a narrow ridge.",
    "An ever-present icefall plugs the shoulder between two mountain peaks.",
    "Five miles from the base of the range towers a lone butte 200 feet tall.",
    "Nearly perfect spheres of granite poke from the ground. They seem to be placed at random.",
    "Five skulls sit in a line on a flat rock. They are weathered, old and all look in the same direction.",
    "The trail gives way to a gap created by a previous avalanche. The ground is unstable.",
    "Green and grey swirled marble forms a nearby smooth cliff face.",
    "This mountain sprouts a broken crag of bare rock, at the foot of which gapes the mouth of a 100-foot-wide cave.",
    "Fast-running rapids have cut a deep channel fifteen-foot-wide into this valley’s floor."
];

export const swamp = [
        "The mire smells particularly odious here.",
        "A fallen rotten tree lies in the muck. Small (harmless) snakes dwell among its roots.",
        "A low bank of thick, cloying mud emerges from the mire. Animal tracks mar its surface.",
        "The dirty water hides a deep pool. Unwary characters may fall into it.",
        "A partially collapsed, abandoned hovel squats atop a small hillock.",
        "Faint mist hovers above the swamp.",
        "The sound of splashing emanates from behind a thick tangle of reeds and tall grasses.",
        "As the characters pass a tree, a sodden, rotten branch gives way and falls into a puddle.",
        "A dry hummock rises above the swamp’s waters; several small trees grow atop it.",
        "An area of deep bog surrounds a large pool of stagnant water. Many small fish swim therein.",
        "A narrow, raised trail cuts through the swamp for about a half-mile.",
        "The trail leads into a deep, muddy pool.",
        "Wide drag marks cut across the trail—a large slithering or crawling creature passed this way several days ago.",
        "The rotting, severed head of a lizardfolk warrior lies partially obscured in high grass.",
        "A small hummock is surrounded by light vegetation. A built but unused campfire stands atop the hummock.",
        "A huge tree concealing a hunter’s blind rises from the mire.",
        "A long-dead animal’s bleached, mouldering bones lie partially buried in the mire.",
        "The trail passes through a thick growth of reeds in a soggy, low-lying area.",
        "A huge footprint from a massive, clawed creature mars a muddy bank.",
        "The branches of several large trees hang over the trail, forming a curtain of sorts and obscuring sight of what lies beyond.",
        "A partially uncovered pit trap filled with rotten wooden stakes blocks the path.",
        "The characters discover a manticore’s skeleton poking above the fetid waters of a deep pool.",
        "An expanse of tall grass stretches several hundred feet to the base of a low ridge. Several sluggish streams flow through the area.",
        "A swathe of thick, viscous sludge slows travel and coats travellers in mud.",
        "A hedge of tall, thick grass hides a deep, sluggish river. Unwary travellers pushing through the hedgerow fall into the river.",
        "A jagged tree stump hides within a tangle of reeds. Unwary characters twist their ankle. The injury reduces the character’s speed by half for 1d3 days or until magic is used to heal the injury.",
        "The rotting remains of a rudimentary wooden bridge stretch across a deep water channel.",
        "An overgrown stretch of rotting causeway crosses an area of deep bog.",
        "A rotten tree serves as home to an ant colony.",
        "Two abandoned wooden cabins stand atop a long, low hillock. Scattered bloodstains and the like hint the residents may have met a horrible end.",
        "The jumbled bones of an ancient skirmish poke from a muddy bank. Digging into the bank reveals nothing more of interest.",
        "An unoccupied raft of crude manufacture floats down a deep watercourse.",
        "A conical mound emerges from the mire.",
        "An area of deep mud triples movement costs.",
        "A shallow pool contains three-foot-deep sludge and slime on its bottom. Characters stepping into the pool get a rude surprise.",
        "A rotting boat without any oars is drawn up on a muddy bank.",
        "A large willow tree grows out of the centre of a wide, deep pool.",
        "Clawed lizardfolk footprints are visible in the mud.",
        "A blackened, lightning-blasted tree dominates a high, steep-sided hillock.",
        "Dense reeds hide the entrance to a dismal mud-filled cavern.",
        "A skull decorated with bird feathers hangs from a tree branch on a leather thong. This is a lizardfolk tribal marker.",
        "A crude, reed-wreathed burial mound stands next to the trail.",
        "Half-sunken into the mire, a few stones suggest an ancient stone wall once stood here.",
        "A cluster of hillocks bound a deep, fetid pool thronged with reeds.",
        "The tracks of many birds mar a long, low, glistening bank of mud.",
        "A barely visible half-rotten lizardfolk corpse lies at the bottom of a muddy pool.",
        "A clear pool near the path is filled with wriggling, hungry leeches.",
        "A splatter of dried vomit covers a mossy stone.",
        "The trail passes under a weeping willow. The ground is firm and dry under its boughs.",
        "Steep banks of mud surround an obviously artificial pool. Many fat fish swim in the pool.",
        "A narrow game trail intersects the path.",
        "A broken, rotting spear lies on the path.",
        "Four spears thrust into the mud are each topped by a decomposing head.",
        "The tracks of a gigantic crocodile cross the trail.",
        "Gently jangling bone and strap metal wind chimes hang from a tree’s branches.",
        "A tangled mass of roots and reeds hides a rotting, empty backpack.",
        "An abandoned campsite covers a hillock.",
        "A small wagon lies half sunken in the mire.",
        "A beaver’s mutilated body hangs from a tree.",
        "The partially inscribed Lizardfolk rune for danger has been carved into a tree’s trunk.",
        "A gigantic blast of acid has partially melted a nearby tree.",
        "A pool of stagnant water stands near the trail.",
        "The intricate, very lifelike statue of a man with arms outstretched blocks the trail.",
        "Booted footsteps suddenly start on the trail. They continue for 30 feet before disappearing.",
        "A part-sunken wall emerges from the murk. A large hole has been dug at its base.",
        "A half-flooded pit blocks the trail. Spikes are visible rising above the muddy water within.",
        "A half-built wooden shack stands upon a small hillock surrounded by deep water.",
        "A huge lily pad floats on a fetid lake.",
        "A willow tree grows in the centre of the trail. The trail around either side is very narrow.",
        "A few silver coins glimmer amid the mud.",
        "A spear with a sign in Lizardfolk reading 'Go Back' blocks the trail.",
        "Shallow pools of particularly fetid, muddy water bound the trail.",
        "Tall rushes surround a pool of potable water.",
        "A jumbled mass of bones and rotting equipment marks an ancient battle site.",
        "A naked human corpse lies in the muck.",
        "Bloodstains cover the trail and lead into a nearby muddy pool.",
        "A sinkhole pierces the ground. It leads to a muddy, sunken cavern.",
        "A steep-sided hillock rises out of the swamp. Its zenith provides an excellent vantage point for spying out the surrounding area.",
        "A rusting steel shield—its straps rotten and useless—lies partially hidden by reeds.",
        "A bale of wood tied together with sodden rope lies discarded by a pool.",
        "A nearby tree’s trunk has been half cut through, and consequently, the tree stands lopsidedly.",
        "The trail leads into a flooded section of marsh.",
        "The party discovers an obviously artificial hill; large boulders packed together hold its flanks in place.",
        "The mud beneath the party’s feet oozes black liquid when trod upon.",
        "A partially hollowed-out log lies near a pool.",
        "Drifting patches of vegetation gently float about a large pool.",
        "A stand of ancient, moss-wreathed willow trees dominates the flanks of a long, low hillock.",
        "A crude wood bridge crosses a stream.",
        "Pretty wildflowers cover a low hill near the trail.",
        "A large tree has fallen across the trail. The characters must either clamber over it or detour into the surrounding fetid water.",
        "A great mass of mushrooms grows in the shadow of a steep bank.",
        "Green algae cover the water of a nearby pool.",
        "The trail passes under the outstretched branches of several trees.",
        "A crude face has been carved into the trunk of a large tree dominating a nearby hillock.",
        "At night, the algae in a pool near the party’s camp are revealed to be phosphorous.",
        "An empty water flask is half-buried in the mud.",
        "Several thick wooden poles have been set into the mud in a rough circle for some unknown reason.",
        "A watchtower’s crumbling ruin dominates a low ridge of stone and hard-packed earth.",
        "Reeds near the path are crushed and broken as if something huge moved through the area.",
        "Blazing sunlight suddenly breaks out from behind a cloud, briefly dazzling the party."
        
    
]

export const desert = [
    "A dead rattlesnake lies coiled at the bottom of a shallow sinkhole.",
    "Several animal skeletons lie around a small oasis.",
    "The merciless sun has fused the top layer of sand into glass.",
    "Four gnolls riding huge hyenas crest a nearby dune. At the sight of the party, they retreat.",
    "A gigantic bird flies overhead, clutching a dead camel in its talons.",
    "A welcoming oasis turns out to be nothing more than a mirage.",
    "A dry well stands in the middle of some ruins.",
    "A giant scorpion scuttles into view.",
    "Cries for help lead to two men buried in the desert sand up to their necks.",
    "An eroded statue of an eagle-headed man stares off into the distance.",
    "A lamia shelters from the searing sun in the shade of a dune.",
    "The party discovers an abandoned campfire; it is nothing but embers now.",
    "A recent sandstorm has unearthed a black monolith covered with strange, unreadable sand-worn inscriptions.",
    "The skeleton of a colossal creature sprawls across the sand.",
    "A troupe of wandering merchants ask to travel with the party for protection.",
    "The soft sand is deep in this part of the desert and counts as difficult terrain.",
    "Clicking sounds from over the dune reaches the party's ears.",
    "An ancient ruined watchtower is partially buried by sand.",
    "Camel-riding slavers question the party concerning escaped slaves.",
    "The sand comes alive as several hungry scarab swarms emerge.",
    "Giant ants devour a dead camel.",
    "A small oasis lies in the lee of the next dune.",
    "A tablet with mostly worn-off hieroglyphs lies halfway down a dune.",
    "A recent sandstorm has revealed a cave entrance.",
    "A large patch of sand feels cold to the touch.",
    "A pack of hyenas pick up the party’s scent.",
    "A burnt-out shipwreck lies halfway down a dune.",
    "Ten-foot-high cacti form a thorny desert forest.",
    "The party must cross a wadi; the dry riverbed has steep sides.",
    "A severe sandstorm makes travel impossible unless the party possesses magical protection.",
    "A randomly determined character falls into a patch of cacti and takes 1d6 damage.",
    "A madman in fine clothes wanders under the searing sun.",
    "A crude wooden tower stands in the lee of a dune.",
    "A ruined stone aqueduct juts from the sand at an odd angle.",
    "A djinni sits in front of a chessboard; he invites a character to play.",
    "The party discovers a scene of carnage and bloodshed; a caravan has been raided. Both men and camels have been put to the sword; nothing of value remains. (A gnoll raiding party is responsible and has carried away the caravan's survivors as slaves and food).",
    "Screaming curses, a frightened, half-naked, sunburnt gnome rushes into view.",
    "A wooden sign proclaims, 'Hell’s Courtyard'.",
    "A shredded backpack lies in the sand.",
    "A ruined tower floats several feet above the sand.",
    "Black smoke rises from the north.",
    "A small bird peeks out from its nest in a cactus.",
    "The partially eaten carcass of a small brass dragon bears signs of electricity damage.",
    "The wind is scorching hot today.",
    "Several fire elementals fight for territory a few hundred feet from the campsite during the night.",
    "An efreeti rampages through the dunes; he looks for something.",
    "A skull tops a wooden pole.",
    "Bones litter the sand in front of a cave entrance.",
    "A veritable maze of man-sized hoodoos rises from the desert sand. It is hard to shake the impression that some are disturbingly humanoid in shape.",
    "The wind has revealed an ancient battleground. It has been looted, and only bones remain.",
    "A huge hyena guards a cave.",
    "Crumbling ruins surround a mine entrance.",
    "The desert divides, and a long canyon stretches out ahead of the party. The shadowed canyon provides a welcome respite from the heat.",
    "A small stepped pyramid stands on the horizon.",
    "Several animal-headed statues lie in the sand. They seem to have been toppled on purpose, and some have been defaced.",
    "During the night, a bright light from an unknown source projects up into the night sky.",
    "This abandoned oasis is an illusion.",
    "A blanket of black smoke covers the desert ahead; it seems the ground itself is on fire.",
    "Confused and muddled tracks cut across the party’s route.",
    "An abandoned wooden palisade in severe disrepair stands atop a dune.",
    "A sandstone tower stands between two dunes.",
    "Wearing torn and bloodied clothes, a gaunt man runs towards the party, repeatedly screaming, 'It is coming. It is coming'.",
    "A discarded bronze amulet lies on the sand. It is scorchingly hot to the touch.",
    "The ground trembles slightly.",
    "Four camel riders observe the party from afar. The camels have blue arcane protective symbols painted on their fur.",
    "A sandstorm assails the party for 1d3 hours.",
    "Four desiccated corpses lie around a campfire; they are long dead and have nothing to loot.",
    "Clouds gather, and thunder and lightning follow, but precipitation does not.",
    "A line of rocks pierce the desert sand.",
    "A broad wadi cuts across the party's route.",
    "At dawn, clawed humanoid footprints are discovered within the party's camp; the guards saw nothing.",
    "A small whirlwind spells out the word 'Help' in the sand before abruptly dying away.",
    "A mournful howl greets the rising sun.",
    "Suddenly, the tall dune the party is traversing collapses. Treat this as an avalanche, but reduce by half the time taken to dig out buried characters.",
    "The party comes upon a collection of ruins. A tent town stands nearby, and a dig is in progress.",
    "A dwarf has been tied to a hoodoo and left to die of exposure.",
    "A rope leads 20 feet up into the empty sky.",
    "The shade from a huge tree protects the dried-out husk of a dead dwarf.",
    "A permanent illusion covers an area of quicksand.",
    "An abandoned oasis, all the irrigation canals filled with sand, squats forlornly in a hollow.",
    "A dead nomad grasps a sand-blasted scroll in his wizened hands.",
    "A wizard calmly walks around, drawing sigils in the sand, with his staff.",
    "Two desert giants demand the party leave their territory immediately.",
    "A blue dragon flies over the party.",
    "A massive earthquake has split open a flat rock, revealing a tunnel leading steeply downwards.",
    "The sand gives way to reveal a 400 ft. long rift, the bottom of which cannot be seen.",
    "The party comes upon a nomad camp; the inhabitants are friendly and offer refreshments.",
    "A sphinx challenges the party to a duel of riddles.",
    "Jets of steam randomly shoot up from the ground; anyone caught in a blast suffers 4d6 fire damage.",
    "During the night, several small flames sprout from the flat expanse of sand. Local nomads believe these are the souls of those taken by the desert, trying to escape to the afterlife.",
    "A long, graceful stone bridge crosses nothing but sandy dunes.",
    "Unidentifiable arcane symbols surround the top of a low stone pyramid.",
    "In the morning, a random character is stung by a small scorpion, which had sought shelter in their clothes during the night.",
    "In the distance, two dragons fight a ferocious battle in the sky.",
    "The party is caught in a sirocco; the fiery hot duststorm deals 1d6 fire damage per minute of exposure (and lasts for 1d10 minutes).",
    "Stones are arranged in arcane patterns only visible from the air.",
    "A green crystal spire pierces the monotonous sandy landscape.",
    "The party finds a summoning circle drawn in the sand; it seems incomplete, as if something has broken out.",
    "The party spend the night in an oasis populated by fey. The night is a drunken revel, but the oasis and all in it disappears at dawn.",
    "Suddenly, the sand beneath the party’s feet forms a large hole. Anyone falling in takes damage (2d6 from a 20 ft. fall) and finds themselves in a large hall built of sandstone. In the northern wall, a doorway offers the prospect of adventure."
];