const soundList = [
  "Bang or slam",
  "Bellowing",
  "Buzzing",
  "Chanting",
  "Chiming",
  "Chirping",
  "Clanking",
  "Clashing",
  "Clicking",
  "Coughing",
  "Creaking",
  "Drumming",
  "Footsteps ahead",
  "Footsteps approaching",
  "Footsteps behind",
  "Footsteps receding",
  "Footsteps to the side",
  "Giggling (faint)",
  "Gong",
  "Grating",
  "Groaning",
  "Grunting",
  "Hissing",
  "Horn or trumpet sounding",
  "Howling",
  "Humming",
  "Jingling",
  "Knocking",
  "Laughter",
  "Moaning",
  "Murmuring",
  "Music",
  "Rattling",
  "Ringing",
  "Rustling",
  "Scratching or scrabbling",
  "Screaming",
  "Scuttling",
  "Shuffling",
  "Slithering",
  "Snapping",
  "Sneezing",
  "Sobbing",
  "Splashing",
  "Splintering",
  "Squeaking",
  "Squealing",
  "Tapping",
  "Thud",
  "Thumping",
  "Tinkling",
  "Twanging",
  "Whining",
  "Whispering",
  "Whistling"
];

export const airList = [
  "Clear and damp",
  "Clear and drafty",
  "Clear but cold",
  "Foggy or misty and cold",
  "Clear, with mist covering floor",
  "Clear and warm",
  "Hazy and humid",
  "Smoky or steamy",
  "Clear, with smoke covering ceiling",
  "Clear and windy"
];

export const smellList = [
  "Acrid",
  "Chlorine",
  "Dank or moldy",
  "Earthy",
  "Manure",
  "Metallic",
  "Ozone",
  "Putrid",
  "Rotting vegetation",
  "Salty and wet",
  "Smoky",
  "Stale",
  "Sulfurous",
  "Urine"
];

export const debrisList = [
  "Arrow, broken",
  "Ashes",
  "Bones",
  "Bottle, broken",
  "Chain, corroded",
  "Club, splintered",
  "Cobwebs",
  "Coin, copper",
  "Cracks, ceiling",
  "Cracks, floor",
  "Cracks, wall",
  "Dagger hilt",
  "Damp ceiling",
  "Dampness, wall",
  "Dried blood",
  "Dripping blood",
  "Dung",
  "Dust",
  "Flask, cracked",
  "Food scraps",
  "Fungi (common)",
  "Guano",
  "Hair or fur",
  "Hammer head, cracked",
  "Helmet, badly dented",
  "Iron bar, bent and rusted",
  "Javelin head, blunt",
  "Leather boot",
  "Leaves and twigs",
  "Mold (common)",
  "Pick handle",
  "Pole, broken (5 ft. long)",
  "Pottery shards",
  "Rags",
  "Rope, rotten",
  "Rubble and dirt",
  "Sack, torn",
  "Slime (harmless)",
  "Spike, rusted",
  "Sticks",
  "Stones, small",
  "Straw",
  "Sword blade, broken",
  "Teeth or fangs, scattered",
  "Torch stub",
  "Wall scratchings",
  "Water, large puddle",
  "Water, small puddle",
  "Water, trickle",
  "Wax blob (candle stub)",
  "Wax drippings",
  "Wood pieces, rotting"
];

export const generalFurnishings = [
  "Altar",
  "Armchair",
  "Armoire",
  "Arras or curtain",
  "Bag",
  "Barrel (40 gallons)",
  "Bed",
  "Bench",
  "Blanket",
  "Box (large)",
  "Brazier and charcoal",
  "Bucket",
  "Buffet cabinet",
  "Bunks",
  "Butt (huge cask, 125 gallons)",
  "Cabinet",
  "Candelabrum",
  "Carpet (large)",
  "Cask (40 gallons)",
  "Chandelier",
  "Charcoal",
  "Chair, plain",
  "Chair, padded",
  "Chair, padded, or divan",
  "Chest, large",
  "Chest, medium",
  "Chest of drawers",
  "Closet (wardrobe)",
  "Coal",
  "Couch",
  "Crate",
  "Cresset",
  "Cupboard",
  "Cushion",
  "Dais",
  "Desk",
  "Fireplace and wood",
  "Fireplace with mantle",
  "Firkin (small cask, 10 gallons)",
  "Fountain",
  "Fresco",
  "Grindstone",
  "Hamper",
  "Hassock",
  "Hogshead (large cask, 65 gallons)",
  "Idol (large)",
  "Keg (small barrel, 20 gallons)",
  "Loom",
  "Mat",
  "Mattress",
  "Pail",
  "Painting",
  "Pallet",
  "Pedestal",
  "Pegs",
  "Pillow",
  "Pipe (large cask, 105 gallons)",
  "Quilt",
  "Rug (small or medium)",
  "Rushes",
  "Sack",
  "Sconce",
  "Screen",
  "Sheet",
  "Shelf",
  "Shrine",
  "Sideboard",
  "Sofa",
  "Staff, normal",
  "Stand",
  "Statue",
  "Stool, high",
  "Stool, normal",
  "Table, large",
  "Table, long",
  "Table, low",
  "Table, round",
  "Table, small",
  "Table, trestle",
  "Tapestry",
  "Throne",
  "Trunk",
  "Tub",
  "Tun (huge cask, 250 gallons)",
  "Urn",
  "Wall basin and font",
  "Wood billets",
  "Workbench"
];

export const religiousArticles = [
  "Altar",
  "Bells",
  "Brazier",
  "Candelabra",
  "Candles",
  "Candlesticks",
  "Cassocks",
  "Chimes",
  "Cloth, altar",
  "Columns or pillars",
  "Curtain or tapestry",
  "Drum",
  "Font",
  "Gong",
  "Holy or unholy symbol",
  "Holy or unholy writings",
  "Idol",
  "Incense burner",
  "Kneeling bench",
  "Lamp",
  "Lectern",
  "Mosaic",
  "Offertory container",
  "Paintings or frescoes",
  "Pews",
  "Pipes, musical",
  "Prayer rug",
  "Pulpit",
  "Rail",
  "Robes",
  "Screen",
  "Shrine",
  "Side chairs",
  "Stand",
  "Statue",
  "Throne",
  "Thurible",
  "Tripod",
  "Vestments",
  "Votive light",
  "Whistle"
];

export const mageFurnishings = [
  "Alembic",
  "Balance and weights",
  "Beaker",
  "Bellows",
  "Book",
  "Bottle",
  "Bowl",
  "Box",
  "Brazier",
  "Cage",
  "Candle",
  "Candlestick",
  "Cauldron",
  "Chalk",
  "Crucible",
  "Crystal ball",
  "Decanter",
  "Desk",
  "Dish",
  "Flask or jar",
  "Funnel",
  "Furnace",
  "Herbs",
  "Horn",
  "Hourglass",
  "Jug",
  "Kettle",
  "Ladle",
  "Lamp or lantern",
  "Lens (concave or convex)",
  "Magic circle",
  "Mortar and pestle",
  "Pan",
  "Parchment",
  "Pentacle",
  "Pentagram",
  "Pipe, smoking",
  "Pot",
  "Prism",
  "Quill",
  "Retort",
  "Rod, mixing or stirring",
  "Scroll",
  "Sextant",
  "Skull",
  "Spatula",
  "Spoon, measuring",
  "Stand",
  "Stool",
  "Stuffed animal",
  "Tank (container)",
  "Tongs",
  "Tripod",
  "Tube (container)",
  "Tube (piping)",
  "Tweezers",
  "Vial",
  "Water clock",
  "Wire",
  "Workbench"
];

const utensilsAndPersonalItems = [
  "Awl",
  "Bandages",
  "Basin",
  "Basket",
  "Book",
  "Bottle",
  "Bowl",
  "Box",
  "Brush",
  "Candle",
  "Candle snuffer",
  "Candlestick",
  "Cane or walking stick",
  "Case",
  "Casket (small)",
  "Coffer",
  "Cologne or perfume",
  "Comb",
  "Cup",
  "Decanter",
  "Dish",
  "Ear spoon",
  "Ewer",
  "Flagon, mug, or tankard",
  "Flask or jar",
  "Food",
  "Fork",
  "Grater",
  "Grinder",
  "Horn, drinking",
  "Hourglass",
  "Jug or pitcher",
  "Kettle",
  "Key",
  "Knife",
  "Knucklebones or dice",
  "Ladle",
  "Lamp or lantern",
  "Mirror",
  "Needle(s)",
  "Oil, cooking",
  "Oil, fuel",
  "Oil, scented",
  "Pan",
  "Parchment",
  "Pipe, musical",
  "Pipe, smoking",
  "Plate, platter, or saucer",
  "Pot",
  "Pouch",
  "Powder puff",
  "Quill",
  "Razor",
  "Rope",
  "Salve or unguent",
  "Scroll",
  "Shaker",
  "Sifter or strainer",
  "Soap",
  "Spigot",
  "Spoon",
  "Stopper",
  "Statuette or figurine",
  "Thread",
  "Tinderbox (with flint and steel)",
  "Towel",
  "Tray",
  "Trivet or tripod",
  "Tureen",
  "Twine",
  "Vase",
  "Vial",
  "Washcloth",
  "Whetstone",
  "Wig",
  "Wool",
  "Yarn"
];

export const containerContents = [
  "Ash",
  "Bodily organs",
  "Bones",
  "Crystals",
  "Gelatin",
  "Grease",
  "Liquid, thin",
  "Liquid, viscous",
  "Oil",
  "Powder",
  "Skin or hide",
    "Spoiled Meat",
    "Spoiled Cheese",
    "Spoiled Root Vegetables",
    "Preserved Meat",
    "Preserved Fruit",
    "Tainted Water",
    "Wine",
    "Cider",
    "Spirits",
    "50 ft Hemp Rope",
    "A Severely Scratched Mirror",
    "Potion of Healing, labeled in something other than common",
    "Potion of Jumping, labeled in something other than common",
    "Poison, labeled in something other than common",
    "Antitoxin",
    "Bullseye lantern",
    "Torches",
    "Hooded lantern",
    "Tinderbox",
    "Fishing supplies",
    "Hunting Trap",
    "Rice",
    "Barley",
    "Wheat",
    "Millet",
    "Iron Ingot",
    "Copper Ingot",
];

export const booksScrollsTomes = [
  "Account records",
  "Alchemist’s notebook",
  "Almanac",
  "Bestiary",
  "Biography",
  "Book of heraldry",
  "Book of myths",
  "Book of pressed flowers",
  "Calendar",
  "Catalog",
  "Contract",
  "Diary",
  "Dictionary",
  "Doodles or sketches",
  "Forged document",
  "Grammar workbook",
  "Heretical text",
  "Historical text",
  "Last will and testament",
  "Legal code",
  "Letter",
  "Lunatic’s ravings",
  "Magic tricks (not a spellbook)",
  "Magic scroll",
  "Map or atlas",
  "Memoir",
  "Navigational chart or star chart",
  "Novel",
  "Painting",
  "Poetry",
  "Prayer book",
  "Property deed",
  "Recipe book or cookbook",
  "Record of a criminal trial",
  "Royal proclamation",
  "Sheet music",
  "Spellbook",
  "Text on armor making",
  "Text on astrology",
  "Text on brewing",
  "Text on exotic flora or fauna",
  "Text on herbalism",
  "Text on local flora",
  "Text on mathematics",
  "Text on masonry",
  "Text on medicine",
  "Theological text",
  "Tome of forbidden lore",
  "Travelogue for an exotic land",
  "Travelogue of the planes"
];
